# Generated by Django 3.2 on 2022-08-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bycicle_info',
            fields=[
                ('position', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('rack_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Brack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bycicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bycicle_info')),
            ],
        ),
    ]
