# Generated by Django 3.2 on 2022-08-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('social_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='소셜사용자_id')),
                ('social_type', models.CharField(max_length=20, verbose_name='소셜 타입')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='이메일')),
            ],
        ),
    ]
